# Generated by Django 3.2.9 on 2021-11-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='fb_id',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
