# Generated by Django 3.2.9 on 2021-11-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_people_fb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='weight',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
