# Generated by Django 3.2.9 on 2021-11-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_people_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caremessage',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='member_id',
        ),
    ]
