# Generated by Django 3.2.9 on 2021-11-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20211112_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='badge',
            field=models.CharField(default=87, max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='emailcheck',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='emailcheckcode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='fb_id',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='fcm_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='group',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='height',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='must_change_password',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='status',
            field=models.CharField(default='Normal', max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='token',
            field=models.CharField(default='$token', max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='verified',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='weight',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
