# Generated by Django 3.2.9 on 2021-11-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_caremessage_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people'),
        ),
    ]
