# Generated by Django 3.2.9 on 2021-11-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_news_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caremessage',
            name='member_id',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='caremessage',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='member_id',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='message',
            field=models.TextField(default='456', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes_type', models.CharField(choices=[(0, '無'), (1, '糖尿病前期'), (2, '第一型'), (3, '第二型'), (4, '妊娠')], max_length=2, null=True)),
                ('oad', models.TextField(max_length=30, null=True)),
                ('insulin', models.TextField(max_length=30, null=True)),
                ('anti_hypertensives', models.TextField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people')),
            ],
        ),
    ]
