# Generated by Django 3.2.9 on 2021-11-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20211112_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='alc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1c', models.TextField(max_length=30, null=True)),
                ('recorded_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people')),
            ],
        ),
    ]
