# Generated by Django 3.2.9 on 2021-11-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20211115_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alc',
            name='a1c',
        ),
        migrations.AddField(
            model_name='alc',
            name='alc',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
