# Generated by Django 3.2.9 on 2021-11-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20211115_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alc',
            old_name='alc',
            new_name='a1c',
        ),
    ]
