# Generated by Django 3.2.9 on 2021-11-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_rename_alc_alc_a1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='anti_hypertensives',
            field=models.BooleanField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='insulin',
            field=models.BooleanField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='oad',
            field=models.BooleanField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[(0, '男'), (1, '女')], max_length=2, null=True),
        ),
    ]
