# Generated by Django 3.2.9 on 2021-11-15 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20211115_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_recording', models.BooleanField(max_length=30, null=True)),
                ('no_recording_for_a_day', models.BooleanField(max_length=30, null=True)),
                ('over_max_or_under_min', models.BooleanField(max_length=30, null=True)),
                ('after_meal', models.BooleanField(max_length=30, null=True)),
                ('unit_of_sugar', models.BooleanField(max_length=30, null=True)),
                ('unit_of_weight', models.BooleanField(max_length=30, null=True)),
                ('unit_of_height', models.BooleanField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people')),
            ],
        ),
    ]
