# Generated by Django 3.2.9 on 2021-11-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='drug_useds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(0, '糖尿病藥物'), (1, '高血壓藥物')], max_length=2, null=True)),
                ('name', models.CharField(max_length=2, null=True)),
                ('recorded_at', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people')),
            ],
        ),
    ]
