# Generated by Django 3.2.9 on 2021-11-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_alter_drug_useds_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='nid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people')),
            ],
        ),
    ]
