# Generated by Django 3.2.9 on 2021-11-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='uid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='nid',
        ),
    ]
