# Generated by Django 3.2.9 on 2021-11-15 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_auto_20211115_0843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='defult',
            new_name='default',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='weight',
            new_name='Weight',
        ),
        migrations.AddField(
            model_name='bloodduck',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people'),
        ),
        migrations.AddField(
            model_name='bloodsugar',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people'),
        ),
        migrations.AddField(
            model_name='weight',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people'),
        ),
    ]
