# Generated by Django 3.2.9 on 2021-11-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20211115_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='uid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.people'),
        ),
    ]
