# Generated by Django 3.2.9 on 2021-11-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_auto_20211115_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('account', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('fb_id', models.CharField(default=0, max_length=30, null=True)),
                ('status', models.CharField(default='Normal', max_length=30)),
                ('group', models.CharField(max_length=30, null=True)),
                ('birthday', models.CharField(max_length=30, null=True)),
                ('height', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(choices=[(0, '男'), (1, '女')], max_length=2, null=True)),
                ('verified', models.CharField(default=1, max_length=30)),
                ('privacy_policy', models.CharField(default=1, max_length=30)),
                ('must_change_password', models.CharField(default=0, max_length=30)),
                ('badge', models.CharField(default=87, max_length=30)),
                ('relationtype', models.CharField(choices=[(0, '醫師團'), (1, '親友團'), (2, '糖友團')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='people',
            name='uid',
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.CharField(default=0, max_length=30)),
                ('type', models.CharField(choices=[(0, '醫師團'), (1, '親友團'), (2, '糖友團')], max_length=30)),
                ('status', models.CharField(default='Normal', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.uid')),
            ],
        ),
    ]
