# Generated by Django 3.2.9 on 2021-11-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20211115_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='invite_code',
            fields=[
                ('user_name', models.CharField(default=0, max_length=30, primary_key=True, serialize=False)),
                ('code', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
