# Generated by Django 3.2.9 on 2021-11-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_invite_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uid',
            old_name='uid',
            new_name='un',
        ),
    ]
