# Generated by Django 3.2.9 on 2021-11-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_rename_uid_uid_un'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.TextField(choices=[(0, '未確認'), (1, '接受'), (2, '拒絕')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='alc',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bloodduck',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bloodsugar',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='caremessage',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drug_useds',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='relation_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[(0, '未確認'), (1, '接受'), (2, '拒絕')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='uid',
        ),
    ]
