# Generated by Django 3.2.9 on 2021-11-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_auto_20211116_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
