# Generated by Django 3.2.9 on 2021-11-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_default_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default',
            name='user_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
