# Generated by Django 3.2.9 on 2021-11-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_auto_20211116_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='people',
            name='login_times',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='unread_records',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
