# Generated by Django 3.2.9 on 2021-11-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0033_auto_20211116_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='privacy_policy',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
