# Generated by Django 3.2.9 on 2021-11-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_people_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
