# Generated by Django 3.2.9 on 2021-11-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0035_auto_20211116_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='lng',
        ),
        migrations.AddField(
            model_name='diet',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
