# Generated by Django 3.2.9 on 2021-11-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_auto_20211116_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite_code',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='whoami',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
