# Generated by Django 3.2.9 on 2021-11-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0037_auto_20211116_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requestlist',
        ),
    ]
