# Generated by Django 3.2.9 on 2021-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0038_rename_request_requestlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('report_id', models.CharField(max_length=30, null=True)),
                ('share', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
