# Generated by Django 3.2.9 on 2021-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='share',
        ),
        migrations.AddField(
            model_name='record',
            name='relation_type',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
