# Generated by Django 3.2.9 on 2021-11-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0042_alter_record_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='print_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='relationtype',
            new_name='relation_type',
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='whoami',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
