# Generated by Django 3.2.9 on 2021-11-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0043_auto_20211118_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='uid_id_friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('list_id', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='print_time',
        ),
    ]
