# Generated by Django 3.2.9 on 2021-11-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0044_auto_20211118_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='uid_id_friend',
            name='friend_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
