# Generated by Django 3.2.9 on 2021-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0047_auto_20211118_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='read',
            field=models.CharField(default='false', max_length=2),
        ),
    ]
